#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer InputBuffer {
    uint data[];
} inputBuffer;

layout(set = 0, binding = 1) buffer KeyBuffer {
    uint key[];
} keyBuffer;

layout(set = 0, binding = 2) buffer OutputBuffer {
    uint data[];
} outputBuffer;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    outputBuffer.data[idx] = inputBuffer.data[idx] ^ keyBuffer.key[idx];
}
